/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tabs;

import Connection.CFConnection;
import DAO.DAOLoai;
import Entity.Loai;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class QuanLyLoai extends javax.swing.JPanel {
    CFConnection conn = new CFConnection();
    DAOLoai dAOLoai = new DAOLoai(conn);
    /**
     * Creates new form QuanLyLoaiSanPham
     */
    public QuanLyLoai() {
        initComponents();
        showTable();
    }
    
    private void showTable() {
        //System.out.println("start gets");
        ArrayList<Loai> list = dAOLoai.displayAll();
        
        DefaultTableModel tabbleLoai = (DefaultTableModel) jTableQuanLyLoaiSanPham.getModel();
        tabbleLoai.setRowCount(0);
        
        for(Loai loai: list){
            tabbleLoai.addRow(new Object[]{
                loai.getMaloai(), loai.getTenloai()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldTenLoai = new javax.swing.JTextField();
        jButtonThem = new javax.swing.JButton();
        jButtonTimKiem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableQuanLyLoaiSanPham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMaLoai = new javax.swing.JTextField();

        jButtonThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonTimKiem.setText("Tìm kiếm");
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });

        jButtonSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jTableQuanLyLoaiSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại sản phẩm", "Tên loại sản phẩm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableQuanLyLoaiSanPham);
        if (jTableQuanLyLoaiSanPham.getColumnModel().getColumnCount() > 0) {
            jTableQuanLyLoaiSanPham.getColumnModel().getColumn(0).setResizable(false);
            jTableQuanLyLoaiSanPham.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý loại sản phẩm");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã Loại: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tên Loai: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThem)
                    .addComponent(jButtonSua))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonTimKiem)
                            .addComponent(jButtonXoa))
                        .addGap(18, 18, 18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
        //bắt lỗi để trống text box khi thêm
        if(jTextFieldTenLoai.getText().isEmpty()){
            JOptionPane.showMessageDialog(jButtonSua, " Bạn chưa nhập đủ thông tin trước khi thực hiện việc thêm thông tin loại sản phẩm mới! ");
            return;
        }
        
        Loai loai = new Loai(jTextFieldTenLoai.getText());
        if(dAOLoai.addLoai(loai) == 1){
            JOptionPane.showMessageDialog(jButtonSua, " Thêm thành công! ");
            showTable();
        }    
        else
            JOptionPane.showConfirmDialog(jButtonSua, " Thêm không thành công! ");
        
        jTextFieldMaLoai.setText("");
        jTextFieldTenLoai.setText("");
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
        //bắt lỗi để trống text box khi sửa
        if(jTextFieldMaLoai.getText().isEmpty()){
            JOptionPane.showMessageDialog(jButtonSua, " Bạn chưa nhập đủ thông tin trước khi thực hiện việc sửa thông tin loại sản phẩm! ");
            return;
        }
        
        Loai loai = new Loai(jTextFieldMaLoai.getText(), jTextFieldTenLoai.getText());
        if (dAOLoai.updateLoai(loai) == 1) {
            JOptionPane.showConfirmDialog(jButtonSua, " Sửa thành công! ");
            showTable(); 
        }
            
        else 
            JOptionPane.showConfirmDialog(jButtonSua, " Sửa không thành công! ");
        
        jTextFieldMaLoai.setText("");
        jTextFieldTenLoai.setText("");
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:
        //bắt lỗi để trống text box khi Xóa
        if(jTextFieldMaLoai.getText().isEmpty()){
            JOptionPane.showMessageDialog(jButtonSua, " Bạn chưa nhập đủ thông tin trước khi thực hiện việc xóa thông loại sản phẩm! ");
            return;
        }
        
        if(dAOLoai.removeLoai(jTextFieldMaLoai.getText()) ==1){
            JOptionPane.showConfirmDialog(jButtonSua, " Xóa thành công! ");
            showTable();
        }  
        else
            JOptionPane.showConfirmDialog(jButtonSua, " Xoa không thành công! ");
        
        jTextFieldMaLoai.setText("");
        jTextFieldTenLoai.setText("");
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
        //bắt lỗi để trống text box khi thêm
        if(jTextFieldMaLoai.getText().isEmpty()){
            JOptionPane.showMessageDialog(jButtonSua, " Bạn chưa nhập đủ thông tin trước khi thực hiện việc tìm kiếm thông tin loại sản phẩm! ");
            return;
        }
        
        ArrayList<Loai> list =  dAOLoai.searchLoai(jTextFieldMaLoai.getText());
        DefaultTableModel tabbleLoai = (DefaultTableModel) jTableQuanLyLoaiSanPham.getModel();
        tabbleLoai.setRowCount(0);
        
        for(Loai loai: list){
            tabbleLoai.addRow(new Object[]{
                loai.getMaloai(), loai.getTenloai()
            });
        }
        jTextFieldMaLoai.setText("");
        jTextFieldTenLoai.setText("");
    }//GEN-LAST:event_jButtonTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableQuanLyLoaiSanPham;
    private javax.swing.JTextField jTextFieldMaLoai;
    private javax.swing.JTextField jTextFieldTenLoai;
    // End of variables declaration//GEN-END:variables
}
